// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0BgpPEsX_ak9aL0o0gs4tHMMlymcRL3o',
    appId: '1:682889802273:web:465a1096915a1b4adbe960',
    messagingSenderId: '682889802273',
    projectId: 'finalyearproject-aeafb',
    authDomain: 'finalyearproject-aeafb.firebaseapp.com',
    storageBucket: 'finalyearproject-aeafb.appspot.com',
    measurementId: 'G-GV598FE24E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtrDrfp0aNiMscQZuO0b3rPKX2yjUqf58',
    appId: '1:682889802273:android:d663a4fcfb8136b6dbe960',
    messagingSenderId: '682889802273',
    projectId: 'finalyearproject-aeafb',
    storageBucket: 'finalyearproject-aeafb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhb76h_OjI9Q8dO7ZP_Dn3daS_A2Y8i-w',
    appId: '1:682889802273:ios:b217b862cc94b48bdbe960',
    messagingSenderId: '682889802273',
    projectId: 'finalyearproject-aeafb',
    storageBucket: 'finalyearproject-aeafb.appspot.com',
    iosClientId: '682889802273-bpfuqnruocqjlu3qqanp7v058uo8f45i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyuproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhb76h_OjI9Q8dO7ZP_Dn3daS_A2Y8i-w',
    appId: '1:682889802273:ios:b217b862cc94b48bdbe960',
    messagingSenderId: '682889802273',
    projectId: 'finalyearproject-aeafb',
    storageBucket: 'finalyearproject-aeafb.appspot.com',
    iosClientId: '682889802273-bpfuqnruocqjlu3qqanp7v058uo8f45i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyuproject',
  );
}
