List<String> academicYear = [
  'Year one(1)',
  'Year two(2)',
  'Year three(3)',
  'Year four(4)',
];
List<String> sex = [
  'Male',
  'Female',
];
List<String> maritalStatus = [
  'Single',
  'Married',
  'Seperated',
  'Widowed',
  'Divorced',
];
List<String> semester = [
  'Semester one(1)',
  'Semster two(2)',
];
List<String> disabilityStatus = [
  'Disabled',
  'Not Disabled',
];

List<String> hallOfAttachment = [
  'Kulubya Hall',
  'Nanziri Hall',
  'Pearl Hall',
  'North Hall',
  'Mandela Hall',
];

List<String> residentialStatus = [
  'Resident',
  'Non-Resident',
];
List<String> homeDistrict = [
  'Buikwe',
  'Bukomansimbi',
  'Butambala',
  'Buvuma',
  'Gomba',
  'Kalangala',
  'Kalungu',
  'Kampala',
  'Kayunga',
  'Kiboga',
  'Kyankwanzi',
  'Luweero',
  'Lwengo',
  'Lyantonde',
  'Masaka',
  'Mityana',
  'Mpigi',
  'Mubende',
  'Mukono',
  'Nakaseke',
  'Nakasongola',
  'Rakai',
  'Sembabule',
  'Wakiso',
  'Amuria',
  'Budaka',
  'Bududa',
  'Bugiri',
  'Bugweri',
  'Bukedea',
  'Bukwo',
  'Bulambuli',
  'Busia',
  'Butaleja',
  'Butebo',
  'Buyende',
  'Iganga',
  'Jinja',
  'Kaberamaido',
  'Kaliro',
  'Kamuli',
  'Kapchorwa',
  'Kapelebyong',
  'Katakwi',
  'Kibuku',
  'Kumi',
  'Kween',
  'Luuka',
  'Manafwa',
  'Mayuge',
  'Mbale',
  'Namayingo',
  'Namisindwa',
  'Namutumba',
  'Ngora',
  'Pallisa',
  'Serere',
  'Sironko',
  'Soroti',
  'Tororo',
  'Abim',
  'Adjumani',
  'Agago',
  'Alebtong',
  'Amolatar',
  'Amudat',
  'Amuru',
  'Apac',
  'Arua',
  'Dokolo',
  'Gulu',
  'Kaabong',
  'Karenga',
  'Kitgum',
  'Koboko',
  'Kole',
  'Kotido',
  'Kwania',
  'Lamwo',
  'Lira',
  'Madi-Okollo',
  'Maracha',
  'Moroto',
  'Moyo',
  'Nabilatuk',
  'Nakapiripirit',
  'Napak',
  'Nebbi',
  'Nwoya',
  'Obongi',
  'Omoro',
  'Otuke',
  'Oyam',
  'Pader',
  'Pakwach',
  'Terego',
  'Yumbe',
  'Zombo',
  'Buhweju',
  'Buliisa',
  'Bundibugyo',
  'Bunyangabu',
  'Bushenyi',
  'Hoima',
  'Ibanda',
  'Isingiro',
  'Kabale',
  'Kabarole',
  'Kagadi',
  'Kakumiro',
  'Kamwenge',
  'Kanungu',
  'Kasese',
  'Kazo',
  'Kibaale',
  'Kikuube',
  'Kiruhura',
  'Kiryandongo',
  'Kisoro',
  'Kitagwenda',
  'Kyegegwa',
  'Kyenjojo',
  'Masindi',
  'Mbarara',
  'Mitooma',
  'Ntoroko',
  'Ntungamo',
  'Rubanda',
  'Rubirizi',
  'Rukiga',
  'Rukungiri',
  'Rwampara',
  'Sheema',
];

List<String> course = [
  'Bachelor of Business Studies with Education',
  'Bachelor of Business Administration',
  'Bachelor of Business Administration',
  'Bachelor of Science in Accounting and Finance',
  'Bachelor of Science in Accounting and Finance',
  'Bachelor of Administrative Science',
  'Bachelor of Procurement and Logistics Management',
  'Bachelor of Management Science',
  'Diploma in Accounting and Finance',
  'Bachelor of Vocational Studies in Agriculture with Education',
  'Bachelor of Vocational Studies in Home Economics with Education',
  'Bachelor of Vocational Studies in Art and Design with Education',
  'Bachelor of Art and Industrial Design',
  'Bachelor of Science in Human Nutrition and Dietetics',
  'Bachelor of Hotel and Institutional Catering',
  'Bachelor of Industrial and Landscape Design',
  'Bachelor of Textile and Apparel Design',
  'Bachelor of Computer and Graphic Design',
  'Diploma in Interior Design',
  'Diploma in Hotel and Institutional Catering',
  'Diploma in Ceramics',
  'Diploma in Textiles Design and Surface Design',
  'Diploma in Fashion and Apparel Design',
  'Diploma in Education Secondary (Home Economics)',
  'Diploma in Education Secondary (Art & Design)',
  'Bachelor of Adult and Community Education',
  'Bachelor of Community Development and Social Justice',
  'Bachelor of Community Based Rehabilitation',
  'Diploma in Community Based Rehabilitation',
  'Diploma in Sign Language Interpreting',
  'Diploma in Mobility and Rehabilitation',
  'Diploma in Deaf Studies',
  'Certificate in Adult and Community Education',
  'Certificate in Deaf Blindness',
  'Bachelor of Science in Oil and Gas Production',
  'Bachelor of Material and Ceramic Science Technology',
  'Bachelor of Science in Leather Tanning Technology',
  'Bachelor of Science Technology – Physics',
  'Bachelor of Science Technology – Chemistry',
  'Bachelor of Science Technology – Biology',
  'Bachelor of Information Technology and Computing',
  'Bachelor of Science with Education (Biological Sciences)',
  'Bachelor of Science with Education (Economics)',
  'Bachelor of Science with Education (Physical Sciences)',
  'Bachelor of Science in Food Processing Technology',
  'Bachelor of Science in Textile and Clothing Technology',
  'Bachelor of Science in Sport and Leisure Management',
  'Bachelor of Science in Sport and Exercise',
  'Bachelor of Environmental Science Technology and Management',
  'Bachelor of Science in Chemical Engineering',
  'Bachelor of Information Systems',
  'Diploma in Science Technology – Physics',
  'Diploma in Science Technology – Chemistry',
  'Diploma in Computer Science',
  'Diploma in Food Processing Technology',
  'Diploma in Material and Ceramic Science Technology Administration',
  'Certificate in Science Laboratory Technology',
  'Certificate in Food Processing Technology',
  'Bachelor of Vocational Studies in Technological Studies with Education.',
  'Bachelor of Engineering in Civil and Building Engineering',
  'Bachelor of Engineering in Mechanical and Manufacturing Engineering',
  'Bachelor of Engineering in Telecommunication Engineering',
  'Bachelor of Science in Building Economics',
  'Bachelor of Engineering in Environmental Engineering and Management',
  'Bachelor of Engineering in Automotive and Power Engineering',
  'Bachelor of Engineering in Industrial',
  'Engineering and Management',
  'Bachelor of Surveying and Land Information Systems',
  'Bachelor of Science in Land Economics',
  'Bachelor of Architecture',
  'Diploma in Electrical Engineering',
  'Diploma in Civil and Building Engineering',
  'Diploma in Mechanical and Production Engineering',
  'Diploma in Computer Engineering',
  'Diploma in Water Engineering',
  'Diploma in Architecture',
  'Diploma in Automobile Engineering',
  'Diploma in Refrigeration and Air Conditioning',
  'Diploma in Telecommunication Engineering',
  'Diploma in Biomedical Engineering',
  'Diploma in Education Secondary (Technological Studies)',
  'Certificate in Printing Technology Chemistry.',
  'Bachelor of Guidance and Counselling',
  'Diploma in Guidance and Counselling',
  'Diploma in Educational Planning and Management',
  'Certificate in Early Childhood Development',
  'Bachelor of Arts',
  'Bachelor of Economics and Statistics',
  'Bachelor of Arts in Social Sciences',
  'Bachelor of Demography & Reproductive Health',
  'Bachelor of Arts in Economics',
  'Bachelor of Arts with Education',
  'Bachelor of Micro Finance',
  'Bachelor of Social Work and Social Administration',
  'Bachelor of Library and Information Science',
  'Diploma in Library and Information Science',
  'Diploma in Education Secondary (French)',
  'Diploma in Micro Finance',
  'Diploma in Music and Theatre Arts',
  'Bachelor of Science in Accounting & Finance',
  'Bachelor of Arts with Education',
  'Bachelor of Business Administration',
  'Diploma in Accounting and Finance',
  'PhD in Religious Studies',
  'Master of Arts in History',
  'Master of Arts in Religious Studies',
  'Master of Arts in Geography',
  'Master of Arts in Literature',
  'Master of Arts in Music Education',
  'Master of Arts in Economics',
  'PhD in Education',
  'Master of Counseling Psychology',
  'Master of Education in Early Childhood Education',
  'Master of Education in Educational Foundations',
  'Master of Organizational Psychology',
  'Master of Education in Policy Plannning & Management',
  'Postgraduate Diploma in Education',
  'Postgraduate Diploma in Educational Leadership',
  'Postgraduate Diploma in Teacher Education',
  'Master of Science in Construction Technology & Management',
  'Master of Science in Advanced Manufacturing systems Engineering',
  'Master of Science in Structural Engineering',
  'Master of Science in Water & Sanitation Engineering',
  'PhD in Food Technology',
  'PhD in Biological Sciences',
  'PhD in Physics',
  'PhD in Chemistry',
  'PhD in Sport science',
  'Master of Science in Chemistry',
  'Master of Science in Conservation & Natural Resource Management.',
  'Master of Science in Food Technology',
  'Master of Science in Physics',
  'Master of Science in Sport Science',
  'Postgraduate Diploma in Food Safety',
  'Postgraduate Diploma in Physical Education & Sports',
  'Postgraduate Diploma in Sports Management',
  'Master of Public Health',
  'Master in Special Needs Education',
  'Postgraduate Diploma in Community Based Rehabilitation',
  'Postgraduate Diploma in Special Needs',
  'Master of Business Administration',
  'Master of Science in Procurement and Supply Chain Management',
  'Master of Science in Organization and Public Sector Management',
  'Master of Science in Agricultural Education & Extension',
  'Master of Science in Animal Production',
  'Master of Science in Soil Science',
  'Master of Science in Crop Science',
  'Master of Science in Human Nutrition',
  'Master of Arts & Industrial Design',
  'Master in Vocational Pedagogy',
  'Postgraduate Diploma in Vocational Pedagogy',
];
List<String> typeOfEntry = [
  "O'Level",
  'Certificate',
  "A'Level",
  'Diploma',
];
List<String> faculty = [
  'Faculty of Engineering',
  'Faculty of Science',
  'Faculty of Agriculture',
  'Faculty of Special Needs & Rehabilitation',
  'Faculty of Arts and Humanities',
  'Faculty of Social Sciences',
  'School of Education',
  'School of Art and Industrial Design',
  'School of Management & Entrepreneurship (SOME)',
  'School of Built Environment (SOFBE)',
  'School of Computing and Information Science (SCIS)',
  'School of Vocational Studies (SOVS)',
  'Institute of Distance Education, E-Learning & Learning Centres (IDAEL)',
];
List<String> expectedAward = [
  'Certificate',
  'Diploma',
  'Degree',
  'Masters',
  'PHD',
];
